param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectPath,

    [Parameter(Mandatory = $true)]
    [string]$PublishDir,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = "Stop"

function Convert-ToNsisString([string]$Value) {
    if ($null -eq $Value) {
        return ""
    }

    return $Value.Replace('$', '$$').Replace('"', '$\"')
}

function Convert-ToVersion4([string]$Value) {
    if ([string]::IsNullOrWhiteSpace($Value)) {
        return "1.0.0.0"
    }

    $parts = $Value.Split('.') | ForEach-Object {
        if ($_ -eq '*') {
            "0"
        }
        elseif ($_ -match '^\d+$') {
            $_
        }
        else {
            "0"
        }
    }

    while ($parts.Count -lt 4) {
        $parts += "0"
    }

    return ($parts | Select-Object -First 4) -join '.'
}

$projectFullPath = (Resolve-Path -LiteralPath $ProjectPath).Path
$publishFullPath = (Resolve-Path -LiteralPath $PublishDir).Path
$projectDir = Split-Path -Parent $projectFullPath

[xml]$project = Get-Content -LiteralPath $projectFullPath -Raw
$properties = $project.Project.PropertyGroup | Select-Object -First 1

$appName = if ($properties.AssemblyName) { [string]$properties.AssemblyName } else { [IO.Path]::GetFileNameWithoutExtension($projectFullPath) }
$exePath = Join-Path $publishFullPath "$appName.exe"

if (!(Test-Path -LiteralPath $exePath)) {
    throw "Published executable not found: $exePath"
}

$versionInfo = (Get-Item -LiteralPath $exePath).VersionInfo
$version = if ($versionInfo.FileVersion) { $versionInfo.FileVersion } else { [string]$properties.AssemblyVersion }
$version4 = Convert-ToVersion4 $version
$company = if ($versionInfo.CompanyName) { $versionInfo.CompanyName } else { [string]$properties.Company }
$copyright = if ($versionInfo.LegalCopyright) { $versionInfo.LegalCopyright } else { [string]$properties.Copyright }
$repositoryUrl = [string]$properties.RepositoryUrl
$authors = [string]$properties.Authors

$outputDir = Split-Path -Parent $OutputPath
if (![string]::IsNullOrWhiteSpace($outputDir)) {
    New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
}

$lines = @(
    "; This file is generated by Generate-NsisMetadata.ps1. Do not edit by hand.",
    "!define APP_NAME `"$(Convert-ToNsisString $appName)`"",
    "!define APP_EXE `"$(Convert-ToNsisString ([IO.Path]::GetFileName($exePath)))`"",
    "!define APP_VERSION `"$(Convert-ToNsisString $version)`"",
    "!define APP_VERSION4 `"$(Convert-ToNsisString $version4)`"",
    "!define APP_COMPANY `"$(Convert-ToNsisString $company)`"",
    "!define APP_AUTHORS `"$(Convert-ToNsisString $authors)`"",
    "!define APP_COPYRIGHT `"$(Convert-ToNsisString $copyright)`"",
    "!define APP_REPOSITORY_URL `"$(Convert-ToNsisString $repositoryUrl)`"",
    "!define APP_PROJECT_DIR `"$(Convert-ToNsisString $projectDir)`"",
    "!define APP_PUBLISH_DIR `"$(Convert-ToNsisString $publishFullPath)`""
)

[IO.File]::WriteAllLines($OutputPath, $lines, [Text.UTF8Encoding]::new($false))
